name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        target: ["i686-pc-windows-msvc", "i686-pc-windows-gnu", "x86_64-pc-windows-msvc", "x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl"]
    steps:
    - uses: actions/checkout@v2
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose
    - name: Run tests
      run: cargo test --target ${{ matrix.target }} --verbose
